# Generated by Django 5.0.3 on 2024-03-10 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='nombre',
            field=models.CharField(default='', max_length=255),
        ),
    ]
