# Generated by Django 5.0.3 on 2024-03-10 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_usuarios_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrito',
            name='estado',
            field=models.BooleanField(default=False),
        ),
    ]
